const USER_JOINS          = 'USER_JOINS';
const USER_LEAVES         = 'USER_LEAVES';
const USER_NAME_CHANGED   = 'USER_NAME_CHANGED';

const MESSAGE_RECEIVED    = 'MESSAGE_RECEIVED';
const MESSAGE_SENT        = 'MESSAGE_SENT';

const SOCKET_CONNECTED    = 'SOCKET_CONNECTED';
const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';
const SOCKET_ERROR        = 'SOCKET_ERROR';

module.exports = {
  USER_JOINS,
  USER_LEAVES,
  USER_NAME_CHANGED,
  MESSAGE_RECEIVED,
  MESSAGE_SENT,
  SOCKET_CONNECTED,
  SOCKET_DISCONNECTED,
  SOCKET_ERROR
};
